#!/usr/bin/env bash
set -euo pipefail

export LATENCY_WARMUP="${LATENCY_WARMUP:-5}"
export LATENCY_SAMPLES="${LATENCY_SAMPLES:-60}"
export LATENCY_CONCURRENCY="${LATENCY_CONCURRENCY:-1,3,8}"
export LATENCY_PROFILE="${LATENCY_PROFILE:-probe}"
export LATENCY_POSTGRES_POOL_SIZES="${LATENCY_POSTGRES_POOL_SIZES:-1,2}"
export LATENCY_PATH_DEPTHS="${LATENCY_PATH_DEPTHS:-2,5}"
export LATENCY_PAYLOAD_BYTES="${LATENCY_PAYLOAD_BYTES:-128,2048}"

"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/score.sh" --dev
