//! Build-time scan of the `static/` directory.
//!
//! Walks every file under `static/` and emits Rust source that
//! declares one `ASSETS` slice keyed by URL path (relative to the
//! mount prefix). Each entry pairs an `include_bytes!` reference
//! with a content-type string picked from the file extension.
//!
//! The generated source is included from `src/assets.rs`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()); // safety: build script — Cargo always sets this
    let static_dir = manifest_dir.join("static");

    println!("cargo:rerun-if-changed=static");
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(&static_dir, &static_dir, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::new();
    src.push_str("// @generated by build.rs — DO NOT EDIT BY HAND\n\n");
    src.push_str("pub(crate) const ASSETS: &[(&str, Asset)] = &[\n");

    let mut index_html_abs: Option<PathBuf> = None;
    for (rel_url, abs_path) in &entries {
        if rel_url == "index.html" {
            index_html_abs = Some(abs_path.clone());
            // index.html is served via a dedicated nonce-substituting
            // path; it is not exposed in the asset table to keep the
            // dispatcher's invariants (raw assets are byte-identical
            // to disk; only the HTML template carries placeholders).
            continue;
        }
        let content_type = content_type_for(abs_path);
        let include_path = abs_path.to_string_lossy();
        src.push_str(&format!(
            "    (\"{}\", Asset {{ bytes: include_bytes!(r\"{}\"), content_type: {:?} }}),\n",
            escape_url(rel_url),
            include_path,
            content_type,
        ));
    }
    src.push_str("];\n\n");

    if let Some(path) = index_html_abs {
        src.push_str(&format!(
            "pub(crate) const INDEX_HTML_TEMPLATE: &str = include_str!(r\"{}\");\n",
            path.to_string_lossy(),
        ));
    } else {
        panic!("static/index.html is required");
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap()); // safety: build script — Cargo always sets this
    fs::write(out_dir.join("assets_generated.rs"), src).expect("write assets_generated.rs"); // safety: build script — fail build on write error
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let read_dir = fs::read_dir(dir).expect("read_dir static"); // safety: build script — fail build on read error
    for entry in read_dir {
        let entry = entry.expect("dir entry"); // safety: build script — fail build on bad entry
        let path = entry.path();
        let file_type = entry.file_type().expect("file type"); // safety: build script — fail build on stat error
        if file_type.is_dir() {
            collect(root, &path, out);
        } else if file_type.is_file() {
            // `*.test.js` are colocated Node `node:test` unit tests, not
            // browser assets — never embed or serve them. A path ending in
            // `.test.js` implies its file name does too, so check the path.
            if path.to_str().is_some_and(|p| p.ends_with(".test.js")) {
                continue;
            }
            let rel = path.strip_prefix(root).expect("strip prefix"); // safety: build script — strip_prefix only fails on a logic bug
            // Force forward slashes in the URL key even on Windows hosts.
            let url = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((url, path));
        }
    }
}

fn content_type_for(path: &Path) -> &'static str {
    match path.extension().and_then(|s| s.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("ico") => "image/x-icon",
        Some("webmanifest") => "application/manifest+json",
        Some("json") => "application/json",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("txt") | Some("md") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn escape_url(s: &str) -> String {
    // URL paths in our static tree are limited to filename chars; the
    // only thing we need to defend against in the emitted source is a
    // literal `"` or `\`. Neither appears in disk file names by
    // convention, but escape defensively.
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
