//! Build-time scan of the WebUI static assets.
//!
//! Walks every file under `static/`, builds the generated SPA bundle into
//! OUT_DIR when `webui-v2-beta` is enabled, and emits Rust source that declares
//! one `ASSETS` slice keyed by URL path (relative to the mount prefix). Each
//! entry pairs an `include_bytes!` reference with a content-type string picked
//! from the file extension.
//!
//! The generated source is included from `src/assets.rs`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::thread;
use std::time::{Duration, Instant};

const FRONTEND_COMMAND_TIMEOUT: Duration = Duration::from_secs(10 * 60);
const COMMAND_POLL_INTERVAL: Duration = Duration::from_millis(100);

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()); // safety: build script — Cargo always sets this
    let static_dir = manifest_dir.join("static");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap()); // safety: build script — Cargo always sets this
    let generated_dist_dir = out_dir.join("webui-v2-dist").join("dist");

    println!("cargo:rerun-if-changed=static");
    println!("cargo:rerun-if-changed=frontend/build.mjs");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/package-lock.json");
    println!("cargo:rerun-if-changed=build.rs");

    let webui_enabled = env::var_os("CARGO_FEATURE_WEBUI_V2_BETA").is_some();
    if webui_enabled {
        build_frontend_dist(&manifest_dir, &generated_dist_dir);
    }

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(&static_dir, &static_dir, "", &mut entries);
    if webui_enabled {
        collect(
            &generated_dist_dir,
            &generated_dist_dir,
            "dist",
            &mut entries,
        );
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::new();
    src.push_str("// @generated by build.rs — DO NOT EDIT BY HAND\n\n");
    src.push_str("pub(crate) const ASSETS: &[(&str, Asset)] = &[\n");

    let mut index_html_abs: Option<PathBuf> = None;
    for (rel_url, abs_path) in &entries {
        if rel_url == "index.html" {
            index_html_abs = Some(abs_path.clone());
            // index.html is served via a dedicated nonce-substituting
            // path; it is not exposed in the asset table to keep the
            // dispatcher's invariants (raw assets are byte-identical
            // to disk; only the HTML template carries placeholders).
            continue;
        }
        let content_type = content_type_for(abs_path);
        let include_path = abs_path.to_string_lossy();
        src.push_str(&format!(
            "    (\"{}\", Asset {{ bytes: include_bytes!(r\"{}\"), content_type: {:?} }}),\n",
            escape_url(rel_url),
            include_path,
            content_type,
        ));
    }
    src.push_str("];\n\n");

    if let Some(path) = index_html_abs {
        src.push_str(&format!(
            "pub(crate) const INDEX_HTML_TEMPLATE: &str = include_str!(r\"{}\");\n",
            path.to_string_lossy(),
        ));
    } else {
        panic!("static/index.html is required");
    }

    fs::write(out_dir.join("assets_generated.rs"), src).expect("write assets_generated.rs"); // safety: build script — fail build on write error
}

fn build_frontend_dist(manifest_dir: &Path, dist_dir: &Path) {
    let frontend_dir = manifest_dir.join("frontend");
    let staging_dist_dir = dist_dir.with_extension("building");

    ensure_frontend_dependencies(&frontend_dir);
    if staging_dist_dir.exists() {
        fs::remove_dir_all(&staging_dist_dir).unwrap_or_else(|error| {
            panic!(
                "remove stale staged webui dist {}: {error}",
                staging_dist_dir.display()
            )
        });
    }
    run_command(
        node_command(),
        &["build.mjs"],
        &frontend_dir,
        &[("IRONCLAW_WEBUI_V2_DIST_DIR", &staging_dist_dir)],
    );

    let app_js = staging_dist_dir.join("app.js");
    if !app_js.is_file() {
        panic!("frontend build did not produce {}", app_js.display());
    }
    if dist_dir.exists() {
        fs::remove_dir_all(dist_dir).unwrap_or_else(|error| {
            panic!("remove stale webui dist {}: {error}", dist_dir.display())
        });
    }
    fs::rename(&staging_dist_dir, dist_dir).unwrap_or_else(|error| {
        panic!(
            "move staged webui dist {} to {}: {error}",
            staging_dist_dir.display(),
            dist_dir.display(),
        )
    });
}

fn ensure_frontend_dependencies(frontend_dir: &Path) {
    let node_modules = frontend_dir.join("node_modules");
    let package_json = frontend_dir.join("package.json");
    let package_lock = frontend_dir.join("package-lock.json");
    let install_marker = node_modules.join(".package-lock.json");

    let needs_install = if !node_modules.is_dir() || !install_marker.is_file() {
        true
    } else {
        let marker_modified = modified_time(&install_marker);
        modified_time(&package_lock) > marker_modified
            || modified_time(&package_json) > marker_modified
    };

    if needs_install {
        run_command(
            npm_command(),
            &["ci", "--no-audit", "--no-fund"],
            frontend_dir,
            &[],
        );
    }
}

fn modified_time(path: &Path) -> std::time::SystemTime {
    fs::metadata(path)
        .and_then(|metadata| metadata.modified())
        .unwrap_or_else(|error| panic!("read modified time for {}: {error}", path.display()))
}

fn run_command(command: &str, args: &[&str], cwd: &Path, envs: &[(&str, &Path)]) {
    let display_command = display_command(command, args);
    let mut cmd = Command::new(command);
    cmd.args(args).current_dir(cwd);
    for (key, value) in envs {
        cmd.env(key, value);
    }

    let mut child = cmd.spawn().unwrap_or_else(|error| {
        panic!(
            "failed to run `{}` in {}: {error}",
            display_command,
            cwd.display(),
        )
    });
    let deadline = Instant::now() + FRONTEND_COMMAND_TIMEOUT;
    let status = loop {
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) if Instant::now() >= deadline => {
                let kill_result = child.kill();
                let _ = child.wait();
                match kill_result {
                    Ok(()) => panic!(
                        "`{}` timed out after {} seconds in {}",
                        display_command,
                        FRONTEND_COMMAND_TIMEOUT.as_secs(),
                        cwd.display(),
                    ),
                    Err(error) => panic!(
                        "`{}` timed out after {} seconds in {}, and failed to kill it: {error}",
                        display_command,
                        FRONTEND_COMMAND_TIMEOUT.as_secs(),
                        cwd.display(),
                    ),
                }
            }
            Ok(None) => thread::sleep(COMMAND_POLL_INTERVAL),
            Err(error) => panic!(
                "failed to poll `{}` in {}: {error}",
                display_command,
                cwd.display(),
            ),
        }
    };
    if !status.success() {
        panic!(
            "`{}` failed in {} with status {status}",
            display_command,
            cwd.display(),
        );
    }
}

fn display_command(command: &str, args: &[&str]) -> String {
    std::iter::once(command)
        .chain(args.iter().copied())
        .collect::<Vec<_>>()
        .join(" ")
}

fn npm_command() -> &'static str {
    if cfg!(windows) { "npm.cmd" } else { "npm" }
}

fn node_command() -> &'static str {
    if cfg!(windows) { "node.exe" } else { "node" }
}

fn collect(root: &Path, dir: &Path, url_prefix: &str, out: &mut Vec<(String, PathBuf)>) {
    let read_dir = fs::read_dir(dir).expect("read_dir static"); // safety: build script — fail build on read error
    for entry in read_dir {
        let entry = entry.expect("dir entry"); // safety: build script — fail build on bad entry
        let path = entry.path();
        let file_type = entry.file_type().expect("file type"); // safety: build script — fail build on stat error
        if file_type.is_dir() {
            // `static/dist` is generated output. Cargo embeds the freshly built
            // OUT_DIR copy when WebUI v2 is enabled, so a local ignored
            // source-tree bundle must never win by accident.
            if url_prefix.is_empty()
                && dir == root
                && path.file_name().and_then(|name| name.to_str()) == Some("dist")
            {
                continue;
            }
            collect(root, &path, url_prefix, out);
        } else if file_type.is_file() {
            // `*.test.js` / `*.test.mjs` are colocated Node `node:test` unit
            // tests, not browser assets — never embed or serve them (shipping
            // test-only code to clients is dead weight + needless exposure). A
            // path ending in `.test.js`/`.test.mjs` implies its file name does
            // too, so check the path. The `assets.rs` regression tests that
            // assert `.test.mjs` content read it from disk, not this table.
            if path
                .to_str()
                .is_some_and(|p| p.ends_with(".test.js") || p.ends_with(".test.mjs"))
            {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let rel = path.strip_prefix(root).expect("strip prefix"); // safety: build script — strip_prefix only fails on a logic bug
            // Force forward slashes in the URL key even on Windows hosts.
            let url = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            let url = if url_prefix.is_empty() {
                url
            } else {
                format!("{url_prefix}/{url}")
            };
            out.push((url, path));
        }
    }
}

fn content_type_for(path: &Path) -> &'static str {
    match path.extension().and_then(|s| s.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("ico") => "image/x-icon",
        Some("webmanifest") => "application/manifest+json",
        Some("json") => "application/json",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("txt") | Some("md") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn escape_url(s: &str) -> String {
    // URL paths in our static tree are limited to filename chars; the
    // only thing we need to defend against in the emitted source is a
    // literal `"` or `\`. Neither appears in disk file names by
    // convention, but escape defensively.
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
