//! Build-time scan of the WebUI static assets.
//!
//! Builds the Vite frontend into Cargo's `OUT_DIR` when `webui-v2-beta` is
//! enabled, then emits Rust source that declares one `ASSETS` slice keyed by
//! URL path (relative to the gateway root). Each entry pairs an
//! `include_bytes!` reference with a content-type string picked from the file
//! extension.
//!
//! The generated source is included from `src/assets.rs`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()); // safety: build script — Cargo always sets this
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap()); // safety: build script — Cargo always sets this
    let generated_dist_dir = out_dir.join("webui-v2-frontend-dist");

    println!("cargo:rerun-if-changed=frontend/index.html");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/pnpm-lock.yaml");
    println!("cargo:rerun-if-changed=frontend/pnpm-workspace.yaml");
    println!("cargo:rerun-if-changed=frontend/public");
    println!("cargo:rerun-if-changed=frontend/src");
    println!("cargo:rerun-if-changed=frontend/vite.config.ts");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=SKIP_FRONTEND_BUILD");

    // The WebChat v2 route surface + SPA bundle is folded unconditionally into
    // this crate (it is the whole reason `ironclaw_webui` exists), so the
    // frontend is normally always built — this replaces the former
    // `webui-v2-beta` feature gate the standalone `ironclaw_webui_v2` crate used
    // before the merge. `SKIP_FRONTEND_BUILD=1` opts out for environments with
    // no Node/pnpm toolchain (backend-only dev, docs.rs, minimal CI images); the
    // Rust crate still compiles, it just embeds no SPA assets.
    let webui_enabled = env::var_os("SKIP_FRONTEND_BUILD").is_none();

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if webui_enabled {
        let dist_dir = build_frontend_dist(&manifest_dir, &generated_dist_dir)?;
        validate_frontend_dist(&dist_dir);
        collect(&dist_dir, &dist_dir, "", &mut entries)?;
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::new();
    src.push_str("// @generated by build.rs — DO NOT EDIT BY HAND\n\n");
    src.push_str("pub(crate) const ASSETS: &[(&str, Asset)] = &[\n");

    let mut index_html_abs: Option<PathBuf> = None;
    for (rel_url, abs_path) in &entries {
        if rel_url == "index.html" {
            index_html_abs = Some(abs_path.clone());
            // index.html is served via a dedicated nonce-substituting
            // path; it is not exposed in the asset table to keep the
            // dispatcher's invariants (raw assets are byte-identical
            // to disk; only the HTML template carries placeholders).
            continue;
        }
        let content_type = content_type_for(abs_path);
        let include_path = abs_path.to_string_lossy();
        src.push_str(&format!(
            "    (\"{}\", Asset {{ bytes: include_bytes!(r\"{}\"), content_type: {:?} }}),\n",
            escape_url(rel_url),
            include_path,
            content_type,
        ));
    }
    src.push_str("];\n\n");

    if !webui_enabled {
        src.push_str("pub(crate) const INDEX_HTML_TEMPLATE: &str = \"\";\n");
    } else if let Some(path) = index_html_abs {
        src.push_str(&format!(
            "pub(crate) const INDEX_HTML_TEMPLATE: &str = include_str!(r\"{}\");\n",
            path.to_string_lossy(),
        ));
    } else {
        panic!("Vite frontend build output index.html is required");
    }

    fs::write(out_dir.join("assets_generated.rs"), src)?;
    Ok(())
}

fn build_frontend_dist(
    manifest_dir: &Path,
    generated_dist_dir: &Path,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let frontend_dir = manifest_dir.join("frontend");
    if generated_dist_dir.exists() {
        fs::remove_dir_all(generated_dist_dir)?;
    }
    run_pnpm(&["install", "--frozen-lockfile"], &frontend_dir)?;
    let generated_arg = generated_dist_dir.to_string_lossy().into_owned();
    run_pnpm(
        &[
            "exec",
            "vite",
            "build",
            "--outDir",
            &generated_arg,
            "--emptyOutDir",
        ],
        &frontend_dir,
    )?;
    Ok(generated_dist_dir.to_path_buf())
}

fn validate_frontend_dist(dist_dir: &Path) {
    let missing = required_frontend_dist_files(dist_dir)
        .into_iter()
        .filter(|path| !path.is_file())
        .map(|path| path.display().to_string())
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        panic!(
            "WebUI v2 frontend build output is missing required files:\n  {}",
            missing.join("\n  "),
        );
    }
}

fn required_frontend_dist_files(dist_dir: &Path) -> [PathBuf; 3] {
    [
        dist_dir.join("index.html"),
        dist_dir.join("wallet-connect.html"),
        dist_dir.join("wallet-connect.js"),
    ]
}

fn run_command(command: &str, args: &[&str], cwd: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new(command).args(args).current_dir(cwd).status()?;
    if status.success() {
        return Ok(());
    }

    Err(std::io::Error::other(format!(
        "`{}` failed in {} with status {status}",
        std::iter::once(command)
            .chain(args.iter().copied())
            .collect::<Vec<_>>()
            .join(" "),
        cwd.display(),
    ))
    .into())
}

fn run_pnpm(args: &[&str], cwd: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut corepack_args = Vec::with_capacity(args.len() + 1);
    corepack_args.push("pnpm");
    corepack_args.extend_from_slice(args);
    run_command(corepack_command(), &corepack_args, cwd)
}

fn corepack_command() -> &'static str {
    if cfg!(windows) {
        "corepack.cmd"
    } else {
        "corepack"
    }
}

fn collect(
    root: &Path,
    dir: &Path,
    url_prefix: &str,
    out: &mut Vec<(String, PathBuf)>,
) -> std::io::Result<()> {
    let read_dir = fs::read_dir(dir)?;
    for entry in read_dir {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            if path.file_name().and_then(|name| name.to_str()) == Some(".vite") {
                continue;
            }
            collect(root, &path, url_prefix, out)?;
        } else if file_type.is_file() {
            let rel = path.strip_prefix(root).expect("strip prefix"); // safety: build script — strip_prefix only fails on a logic bug
            // Force forward slashes in the URL key even on Windows hosts.
            let url = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            let url = if url_prefix.is_empty() {
                url
            } else {
                format!("{url_prefix}/{url}")
            };
            out.push((url, path));
        }
    }
    Ok(())
}

fn content_type_for(path: &Path) -> &'static str {
    match path.extension().and_then(|s| s.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("ico") => "image/x-icon",
        Some("webmanifest") => "application/manifest+json",
        Some("json") => "application/json",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("txt") | Some("md") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn escape_url(s: &str) -> String {
    // URL paths in our static tree are limited to filename chars; the
    // only thing we need to defend against in the emitted source is a
    // literal `"` or `\`. Neither appears in disk file names by
    // convention, but escape defensively.
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
